# Generated by Django 2.1.2 on 2018-11-09 10:58

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('original_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
